openapi: 3.0.3
info:
  description: Provides a set of endpoints to manage Devices, Things, Properties and Timeseries
  title: Arduino IoT Cloud binaries_v2 properties API
  version: '2.0'
tags:
- name: properties
paths:
  /iot/v1/properties:
    get:
      description: Returns the list of all properties of the user
      operationId: properties#listAll
      responses:
        '200':
          content:
            application/vnd.arduino.property+json; type=collection:
              schema:
                $ref: '#/components/schemas/ArduinoPropertyCollection'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/ArduinoPropertyCollection'
          description: OK
        '401':
          content:
            application/vnd.arduino.property+json; type=collection:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '404':
          content:
            application/vnd.arduino.property+json; type=collection:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Not Found
        '500':
          content:
            application/vnd.arduino.property+json; type=collection:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      security:
      - oauth2: []
      summary: listAll properties
      tags:
      - properties
components:
  schemas:
    ArduinoProperty:
      description: ArduinoProperty media type (default view)
      properties:
        created_at:
          description: Creation date of the property
          format: date-time
          type: string
        deleted_at:
          description: Delete date of the property
          format: date-time
          type: string
        href:
          description: The api reference of this property
          type: string
        id:
          description: The id of the property
          format: uuid
          type: string
        last_value:
          description: Last value of this property
        linked_to_trigger:
          description: Indicates if the property is involved in the activation of at least a trigger
          type: boolean
        max_value:
          description: Maximum value of this property
          format: double
          type: number
        min_value:
          description: Minimum value of this property
          format: double
          type: number
        name:
          description: The friendly name of the property
          type: string
        permission:
          description: The permission of the property
          type: string
        persist:
          description: If true, data will persist into a timeseries database
          type: boolean
        sync_id:
          description: The id of the sync pool
          format: uuid
          type: string
        tag:
          description: The integer id of the property
          format: int64
          type: integer
        thing_id:
          description: The id of the thing
          format: uuid
          type: string
        thing_name:
          description: The name of the associated thing
          type: string
        type:
          description: The type of the property
          type: string
        update_parameter:
          description: The update frequency in seconds, or the amount of the property has to change in order to trigger an update
          format: double
          type: number
        update_strategy:
          description: The update strategy for the property value
          type: string
        updated_at:
          description: Update date of the property
          format: date-time
          type: string
        value_updated_at:
          description: Last update timestamp of this property
          format: date-time
          type: string
        variable_name:
          description: The sketch variable name of the property
          type: string
      required:
      - id
      - thing_id
      - name
      - type
      - permission
      - update_strategy
      - href
      title: 'Mediatype identifier: application/vnd.arduino.property+json; view=default'
      type: object
    ArduinoPropertyCollection:
      description: ArduinoPropertyCollection is the media type for an array of ArduinoProperty (default view)
      items:
        $ref: '#/components/schemas/ArduinoProperty'
      title: 'Mediatype identifier: application/vnd.arduino.property+json; type=collection; view=default'
      type: array
    error:
      description: Error response media type (default view)
      properties:
        code:
          description: an application-specific error code, expressed as a string value.
          example: invalid_value
          type: string
        detail:
          description: a human-readable explanation specific to this occurrence of the problem.
          example: Value of ID must be an integer
          type: string
        id:
          description: a unique identifier for this particular occurrence of the problem.
          example: 3F1FKVRR
          type: string
        meta:
          additionalProperties: true
          description: a meta object containing non-standard meta-information about the error.
          example:
            timestamp: 1458609066
          type: object
        status:
          description: the HTTP status code applicable to this problem, expressed as a string value.
          example: '400'
          type: string
      title: 'Mediatype identifier: application/vnd.goa.error+json; view=default'
      type: object
externalDocs:
  description: See docs on Confluence
  url: https://arduino.atlassian.net/wiki/spaces/FTWEB/pages/91160610/Arduino+IoT+Cloud
