openapi: 3.0.3
info:
  description: Provides a set of endpoints to manage Devices, Things, Properties and Timeseries
  title: Arduino IoT Cloud binaries_v2 devices_v2_pass API
  version: '2.0'
tags:
- description: Provides a set of endpoints to manage the password of a device
  name: devices_v2_pass
paths:
  /iot/v2/devices/{id}/pass:
    delete:
      description: Removes the password for the device.
      operationId: devices_v2_pass#delete
      parameters:
      - description: The id of the device
        in: path
        name: id
        required: true
        schema:
          type: string
      - in: header
        name: X-Organization
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          content:
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
            text/plain:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          content:
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
            text/plain:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      security:
      - oauth2: []
      summary: delete devices_v2_pass
      tags:
      - devices_v2_pass
    get:
      description: Returns whether the password for this device is set or not. It doesn't return the password.
      operationId: devices_v2_pass#get
      parameters:
      - description: The id of the device
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: If true, return a suggested password
        in: query
        name: suggested_password
        schema:
          default: false
          type: boolean
      - in: header
        name: X-Organization
        schema:
          type: string
      responses:
        '200':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/ArduinoDevicev2Pass'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/ArduinoDevicev2Pass'
          description: OK
        '401':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      security:
      - oauth2: []
      summary: get devices_v2_pass
      tags:
      - devices_v2_pass
    post:
      description: Check if the password matches.
      operationId: devices_v2_pass#check
      parameters:
      - description: The id of the device
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckDevicesV2PassPayload'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckDevicesV2PassPayload'
        required: true
        x-originalParamName: payload
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          content:
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
            text/plain:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '500':
          content:
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
            text/plain:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      security:
      - oauth2: []
      summary: check devices_v2_pass
      tags:
      - devices_v2_pass
    put:
      description: Sets the password for the device. It can never be read back.
      operationId: devices_v2_pass#set
      parameters:
      - description: The id of the device
        in: path
        name: id
        required: true
        schema:
          type: string
      - in: header
        name: X-Organization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/devicev2.pass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/devicev2.pass'
        required: true
        x-originalParamName: payload
      responses:
        '200':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/ArduinoDevicev2Pass'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/ArduinoDevicev2Pass'
          description: OK
        '400':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Bad Request
        '401':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          content:
            application/vnd.arduino.devicev2.pass+json:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Internal Server Error
      security:
      - oauth2: []
      summary: set devices_v2_pass
      tags:
      - devices_v2_pass
components:
  schemas:
    ArduinoDevicev2Pass:
      description: DeviceCertV2 describes a password associated to a device (default view)
      properties:
        set:
          description: Whether the password is set or not
          type: boolean
        suggested_password:
          description: A random suggested password
          type: string
      required:
      - set
      title: 'Mediatype identifier: application/vnd.arduino.devicev2.pass+json; view=default'
      type: object
    devicev2.pass:
      properties:
        password:
          description: The password for the device
          type: string
      title: devicev2.pass
      type: object
    error:
      description: Error response media type (default view)
      properties:
        code:
          description: an application-specific error code, expressed as a string value.
          example: invalid_value
          type: string
        detail:
          description: a human-readable explanation specific to this occurrence of the problem.
          example: Value of ID must be an integer
          type: string
        id:
          description: a unique identifier for this particular occurrence of the problem.
          example: 3F1FKVRR
          type: string
        meta:
          additionalProperties: true
          description: a meta object containing non-standard meta-information about the error.
          example:
            timestamp: 1458609066
          type: object
        status:
          description: the HTTP status code applicable to this problem, expressed as a string value.
          example: '400'
          type: string
      title: 'Mediatype identifier: application/vnd.goa.error+json; view=default'
      type: object
    CheckDevicesV2PassPayload:
      properties:
        password:
          description: The password for the device
          type: string
      required:
      - password
      title: CheckDevicesV2PassPayload
      type: object
externalDocs:
  description: See docs on Confluence
  url: https://arduino.atlassian.net/wiki/spaces/FTWEB/pages/91160610/Arduino+IoT+Cloud
