openapi: 3.0.3
info:
  description: Provides a set of endpoints to manage Devices, Things, Properties and Timeseries
  title: Arduino IoT Cloud binaries_v2 network_credentials_v1 API
  version: '2.0'
tags:
- name: network_credentials_v1
paths:
  /iot/v1/network_credentials/{type}:
    get:
      description: Show required network credentials depending on device type
      operationId: network_credentials_v1#show
      parameters:
      - description: Connection used by the device
        in: query
        name: connection
        schema:
          enum:
          - wifi
          - eth
          - wifiandsecret
          - gsm
          - nb
          - lora
          - catm1
          - cellular
          type: string
      - description: Device type
        in: path
        name: type
        required: true
        schema:
          enum:
          - mkrwifi1010
          - mkr1000
          - nano_33_iot
          - mkrgsm1400
          - mkrwan1310
          - mkrwan1300
          - mkrnb1500
          - lora-device
          - login_and_secretkey_wifi
          - envie_m7
          - nanorp2040connect
          - nicla_vision
          - opta
          - giga
          - portenta_c33
          - unor4wifi
          - nano_nora
          type: string
      responses:
        '200':
          content:
            application/vnd.arduino.credentialsv1+json; type=collection:
              schema:
                $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
          description: OK
        '401':
          content:
            application/vnd.arduino.credentialsv1+json; type=collection:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '404':
          description: Not Found
      summary: show network_credentials_v1
      tags:
      - network_credentials_v1
  /iot/v1/network_credentials/{type}/connections:
    get:
      description: Show available connection types depending on device type
      operationId: network_credentials_v1#showByDevice
      parameters:
      - description: Device type
        in: path
        name: type
        required: true
        schema:
          enum:
          - mkrwifi1010
          - mkr1000
          - nano_33_iot
          - mkrgsm1400
          - mkrwan1310
          - mkrwan1300
          - mkrnb1500
          - lora-device
          - login_and_secretkey_wifi
          - envie_m7
          - nanorp2040connect
          - nicla_vision
          - opta
          - giga
          - portenta_c33
          - unor4wifi
          - nano_nora
          type: string
      responses:
        '200':
          content:
            application/vnd.arduino.arduinoconnections.v1+json:
              schema:
                $ref: '#/components/schemas/ArduinoArduinoconnectionsV1'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/ArduinoArduinoconnectionsV1'
          description: OK
        '401':
          content:
            application/vnd.arduino.arduinoconnections.v1+json:
              schema:
                $ref: '#/components/schemas/error'
            application/vnd.goa.error+json:
              schema:
                $ref: '#/components/schemas/error'
          description: Unauthorized
        '404':
          description: Not Found
      summary: showByDevice network_credentials_v1
      tags:
      - network_credentials_v1
components:
  schemas:
    ArduinoCredentialsv1:
      description: ArduinoCredentialsv1 media type (default view)
      properties:
        friendly_name:
          description: Friendly name
          type: string
        max_length:
          description: Max length of the field expressed in bytes
          format: int64
          type: integer
        required:
          description: Tell if the parameter is required or not
          type: boolean
        secret_name:
          description: The secret parameter name
          type: string
        sensitive:
          description: Tell if the field is sensitive
          type: boolean
      required:
      - secret_name
      - required
      - friendly_name
      - sensitive
      - max_length
      title: 'Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default'
      type: object
    ArduinoArduinoconnectionsV1:
      description: ArduinoArduinoconnectionsV1 media type (default view)
      properties:
        catm1:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        cellular:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        eth:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        gsm:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        lora:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        nb:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        wifi:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
        wifiandsecret:
          $ref: '#/components/schemas/ArduinoCredentialsv1Collection'
      title: 'Mediatype identifier: application/vnd.arduino.arduinoconnections.v1+json; view=default'
      type: object
    error:
      description: Error response media type (default view)
      properties:
        code:
          description: an application-specific error code, expressed as a string value.
          example: invalid_value
          type: string
        detail:
          description: a human-readable explanation specific to this occurrence of the problem.
          example: Value of ID must be an integer
          type: string
        id:
          description: a unique identifier for this particular occurrence of the problem.
          example: 3F1FKVRR
          type: string
        meta:
          additionalProperties: true
          description: a meta object containing non-standard meta-information about the error.
          example:
            timestamp: 1458609066
          type: object
        status:
          description: the HTTP status code applicable to this problem, expressed as a string value.
          example: '400'
          type: string
      title: 'Mediatype identifier: application/vnd.goa.error+json; view=default'
      type: object
    ArduinoCredentialsv1Collection:
      description: ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)
      items:
        $ref: '#/components/schemas/ArduinoCredentialsv1'
      title: 'Mediatype identifier: application/vnd.arduino.credentialsv1+json; type=collection; view=default'
      type: array
externalDocs:
  description: See docs on Confluence
  url: https://arduino.atlassian.net/wiki/spaces/FTWEB/pages/91160610/Arduino+IoT+Cloud
